baseURL = 'https://bdfz.net/'
languageCode = 'en-us'
title = 'Suen'
theme = "bearblog-neo"

enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

[params]
    postSearch = true
    groupByYear = false
    toc = true
    showTitle = true
    showDate = true
    upvote = true
    upvoteURL = "https://upvote.bdfz.net/"
    favicon = "https://raw.githubusercontent.com/gptv/suen/main/images/Avatar-small.jpeg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This allows raw HTML in Markdown, unrelated to CSS loading