baseURL        = "https://bdfz.net/"
languageCode   = "zh-cn"
title          = "Suen"
theme          = "bearblog-neo"
description    = "Suen 的個人博客，隨想，隨寫。"
copyright      = "© 2025 Suen"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name   = "Blog"
    url    = "/posts/"
    weight = 1

[params]
  postSearch   = true
  groupByYear  = false
  toc          = false
  showTitle    = true
  showDate     = true
  upvote       = true
  upvoteURL    = "https://upvote.bdfz.net/"
  favicon      = "https://raw.githubusercontent.com/gptv/suen/main/images/Avatar-small.jpeg"
  dateFormat   = "2006-01-02"
  paginationWindow = 2

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    lineNos   = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[pagination]
  pagerSize      = 20
  disableAliases = false
  path           = "page"

[related]
  threshold    = 80
  includeNewer = true
  toLower      = false
  [[related.indices]]
    name   = "tags"
    weight = 100
  [[related.indices]]
    name   = "categories"
    weight = 80
  [[related.indices]]
    name   = "date"
    weight = 10